### ISSUE TITLE
Do you have the latest version of EFI？

### ISSUE THREAD

**Issue by ghost** [MuntashirAkon/HackintoshDellInspiron5567#1]
Do you have the latest version of EFI？

**Comment by MuntashirAkon** [comment]
Yes, sorry. I've intended to update the repo many times but I can't seem to manage enough time to do that (it needs a bit cleaning up, you know). I will update the repo as soon as possible. Thanks.

**Comment by HeyMickey** [comment]
I don't know why I received this email, but I don't have the latest EFI at present.



发自我的iPhone


------------------ Original ------------------
From: Muntashir Al-Islam ***@***.***&gt;
Date: Tue,Jan 11,2022 3:23 PM
To: MuntashirAkon/HackintoshDellInspiron5567 ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [MuntashirAkon/HackintoshDellInspiron5567] Do you have the latest version of EFI？ (Issue #1)





 
Yes, sorry. I've intended to update the repo many times but I can't seem to manage enough time to do that (it needs a bit cleaning up, you know). I will update the repo as soon as possible. Thanks.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MuntashirAkon** [comment]
> I don't know why I received this email, but I don't have the latest EFI at present.

Probably you're watching the project. Check your watch preferences for this repo.

**Comment by HeyMickey** [comment]
OK，thanku



发自我的iPhone


------------------ Original ------------------
From: Muntashir Al-Islam ***@***.***&gt;
Date: Tue,Jan 11,2022 9:32 PM
To: MuntashirAkon/HackintoshDellInspiron5567 ***@***.***&gt;
Cc: HeyMickey ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [MuntashirAkon/HackintoshDellInspiron5567] Do you have the latest version of EFI？ (Issue #1)

**Comment by MuntashirAkon** [comment]
Updated in 2f8b46e022caa58330a9b991f84387815594afba
