### ISSUE TITLE
Is this the latest MAC OS?

### ISSUE THREAD

**Issue by ghost** [MuntashirAkon/HackintoshDellInspiron5567#2]
Are you using the latest system?

**Comment by HeyMickey** [comment]
No, I haven't operated it for a long time



发自我的iPhone


------------------ Original ------------------
From: hexin1314 ***@***.***&gt;
Date: Sun,May 29,2022 4:42 PM
To: MuntashirAkon/HackintoshDellInspiron5567 ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [MuntashirAkon/HackintoshDellInspiron5567] Is this the latest MAC OS? (Issue #2)





 
Are you using the latest system?

**Comment by MuntashirAkon** [comment]
Currently running **macOS Big Sur** as stated in the README. In fact, I am replying from the build itself. I haven't upgraded to macOS Monterey yet mostly because I do not have enough time to download and install it. You can try it though, it may or may not work.
